# Generated by Django 3.2.4 on 2023-11-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Anonymous', max_length=15, verbose_name='Name'),
        ),
    ]
